### ISSUE TITLE
JSON as source

### ISSUE THREAD

**Issue by mikegoodstadt** [wnyc/Timeline#5]
Hi - beautiful timeline!
Can this script be adapted / extended to use other sources?
eg. [PHP-made JSON](http://lythgoes.net/genealogy/demo9/api_family.php?familyID=F1&tree=) from data on a private server:
many thanks, Mike
(Ed: having an intensive course on what Tabletop actually does... :)

**Comment by etcho** [comment]
mikegoodstadt, I was stucked at the same point. To solve it, I used a library to access the Google Docs's sheet and insert the rows using php.
Were done following this tutorial http://www.farinspace.com/saving-form-data-to-google-spreadsheets/
Maybe helps you too.

**Comment by mikegoodstadt** [comment]
Hi etcho - (sorry about the 5m delay :)
Thanks for the suggestion. All the best in 2013.
With time flying,
Mike
